Repository echo-webkom/echo-web-mono, pull requests merged in 2023-12, with the labels that each got.

#987 Make post chip colorful
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/components/post-preview.tsx
Labels: design 💄

#995 Fix typo in groq
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/app/api/sanity/sync/query.ts
Labels: bug :bug:

#1019 Fix lockfile
  pnpm-lock.yaml
Labels: build 🔧

#1022 Check migrations
  .github/workflows/check-migration.yaml
  .github/workflows/ci.yaml
Labels: ci 🔄

#997 Update mapping
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/app/api/sanity/sync/query.ts
  apps/web/src/app/api/sanity/sync/route.ts
  apps/web/src/lib/is-host.ts
  packages/db/drizzle/migrations/0003_known_shaman.sql
  packages/db/drizzle/migrations/meta/0003_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/happenings-to-groups.ts
  scripts/add-to-group.sh
  scripts/get-id.sh
  scripts/sync.sh
Labels: bug :bug:

#1024 Add new website banner
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:

#1023 Remove scroll from dialog
  apps/web/src/components/ui/dialog.tsx
Labels: design 💄

#1036 Fix posts order
  apps/web/src/sanity/posts/index.ts
Labels: bug :bug:

#985 Zeno/dark mode knapp
  apps/web/package.json
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/providers.tsx
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/mobile-navigation.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/student-group-preview.tsx
  apps/web/src/components/theme-switch-button.tsx
  apps/web/src/styles/globals.css
  pnpm-lock.yaml
Labels: feature :sparkles:, design 💄

#1034 Remove debug field
  apps/web/src/components/register-button.tsx
Labels: bug :bug:

#1041 New selected var in global.css
  apps/web/src/components/happening-preview-box.tsx
  apps/web/src/styles/globals.css
Labels: design 💄

#1045 La til slug for ny info side
  apps/web/src/lib/routes.ts
Labels: manual work :muscle:

#1048 Dark footer color
  apps/web/src/app/layout.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/mobile-navigation.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/theme-switch-button.tsx
  apps/web/src/styles/globals.css
  apps/web/tailwind.config.ts
Labels: design 💄

#1053 Dark mode form
  apps/web/src/components/event-filter.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/components/ui/input.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/ui/textarea.tsx
  apps/web/src/styles/globals.css
Labels: design 💄

#1054 Happening page no db
  apps/web/src/components/happening-sidebar.tsx
Labels: refactoring :recycle:

#1065 Fix pictures
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/sanity/profile/schemas.ts
  apps/web/src/sanity/student-group/index.ts
  apps/web/src/sanity/student-group/schemas.ts
Labels: bug :bug:

#1037 Split date and time in sidebar
  apps/web/src/components/add-to-calender.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/utils/date.ts
Labels: design 💄

#1038 Hide closed registration
  apps/web/src/components/happening-sidebar.tsx
Labels: bug :bug:

#1056 Close nav dropdown
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/hooks/use-outsideclick.ts
Labels: refactoring :recycle:

#1025 Add rate limiter
  .env.example
  apps/web/package.json
  apps/web/src/app/(default)/rate-limited/page.tsx
  apps/web/src/lib/rate-limit.ts
  apps/web/src/middleware.ts
  pnpm-lock.yaml
  turbo.json
Labels: feature :sparkles:

#1051 Add analytics
  apps/web/package.json
  apps/web/src/app/layout.tsx
  pnpm-lock.yaml
Labels: feature :sparkles:

#1092 Remove ratelimit
  apps/web/src/middleware.ts
Labels: bug :bug:
