Repository echo-webkom/echo-web-mono, pull requests merged in 2023-11, with the labels that each got.

#850 fix admin form
  apps/web/src/app/(admin)/admin/brukere/columns.tsx
  apps/web/src/components/ui/switch.tsx
  packages/db/drizzle/migrate.ts
Labels: bug :bug:

#805 Add cookie banner
  apps/web/src/actions/cookies.ts
  apps/web/src/app/(default)/informasjonskapsler/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/components/cookie-banner-client.tsx
  apps/web/src/components/cookie-banner.tsx
  apps/web/src/components/markdown.tsx
  apps/web/src/config.ts
Labels: feature :sparkles:

#859 Fix typo in migrate script
  packages/db/drizzle/migrate.ts
Labels: bug :bug:

#860 New select
  apps/web/package.json
  apps/web/src/app/(default)/tilbakemelding/feedback-form.tsx
  apps/web/src/app/(default)/tilbakemelding/page.tsx
  apps/web/src/components/register-button.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/user-form.tsx
  playwright/web/feedback.spec.ts
  pnpm-lock.yaml
Labels: refactoring :recycle:

#866 Add countdown
  apps/web/src/app/(default)/arrangement/[slug]/event-sidebar.tsx
  apps/web/src/app/(default)/bedpres/[slug]/bedpres-sidebar.tsx
  apps/web/src/app/api/sanity/query.ts
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/components/add-to-calender.tsx
  apps/web/src/components/countdown.tsx
  apps/web/src/components/register-button.tsx
  apps/web/src/components/user-form.tsx
Labels: feature :sparkles:

#873 Links to eventpage from happening-preview-box
  apps/web/src/components/happening-preview-box.tsx
Labels: feature :sparkles:

#878 User can be admin without membership
  apps/web/src/actions/user.ts
Labels: bug :bug:

#849 add more e2e tests
  .env.example
  .github/actions/pnpm-install/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/destroy-preview.yaml
  .github/workflows/preview.yaml
  apps/web/src/actions/update-registration.ts
  apps/web/src/actions/user.ts
  apps/web/src/app/(default)/arrangement/[slug]/event-sidebar.tsx
  apps/web/src/app/(default)/bedpres/[slug]/bedpres-sidebar.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/happening-info-box.tsx
  apps/web/src/components/random-person-button.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/user-menu.tsx
  apps/web/src/lib/queries/happening.ts
  apps/web/src/lib/queries/student-groups.ts
  package.json
  packages/auth/src/auth-options.ts
  packages/db/drizzle/migrate.ts
  packages/db/drizzle/migrations/meta/0002_snapshot.json
  packages/db/drizzle/migrations/meta/0003_snapshot.json
  packages/db/drizzle/migrations/meta/0004_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/drizzle/seed.ts
  playwright/docs/index.spec.ts
  playwright/helpers/sessionTest.ts
  playwright/package.json
  playwright/playwright.config.ts
  playwright/web/index.spec.ts
  playwright/web/login.spec.ts
  playwright/web/profile.spec.ts
  pnpm-lock.yaml
  turbo.json
Labels: testing :test_tube:

#868 Use node postgres
  .github/workflows/ci.yaml
  apps/web/src/app/(default)/[type]/[slug]/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
  apps/web/src/utils/database-status.ts
  package.json
  packages/db/drizzle/check.ts
  packages/db/drizzle/migrate.ts
  packages/db/index.ts
  packages/db/package.json
  pnpm-lock.yaml
Labels: refactoring :recycle:

#931 Herwal/event page styling 2
  apps/web/src/components/event-filter.tsx
Labels: design 💄

#947 use src/index.ts
  apps/web/src/lib/checks/with-basic-auth.ts
  packages/auth/index.ts
  packages/auth/package.json
  packages/auth/src/index.ts
  packages/lib/index.ts
  packages/lib/package.json
  packages/lib/src/index.ts
  packages/lib/tsconfig.json
Labels: refactoring :recycle:

#948 pin deps
  apps/cms/package.json
  apps/web/package.json
  package.json
  packages/auth/package.json
  packages/db/package.json
  packages/email/package.json
  packages/eslint/package.json
  packages/lib/package.json
  playwright/package.json
  pnpm-lock.yaml
Labels: dependencies :handshake:
