Repository echo-webkom/echo-web-mono, pull requests merged in 2023-10, with the labels that each got.

#718 Bump zod
  apps/web/package.json
  pnpm-lock.yaml
Labels: build 🔧

#716 Added link for /om/echo in page
  apps/web/src/app/(landing)/page.tsx
Labels: manual work :muscle:

#734 New menu
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/layout.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/app/(default)/tilbakemelding/page.tsx
  apps/web/src/app/(landing)/page.tsx
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/components/mobile-navigation.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/ui/header-logo.tsx
  apps/web/src/components/ui/header.tsx
Labels: refactoring :recycle:

#762 Add revalidate endpoint
  apps/web/src/app/api/sanity/revalidate/route.ts
  apps/web/src/sanity/client.ts
Labels: feature :sparkles:

#763 Minor changes
  apps/web/src/app/(default)/[type]/[slug]/page.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
  apps/web/src/components/post-preview.tsx
  apps/web/src/components/student-group-preview.tsx
  apps/web/src/lib/routes.ts
Labels: refactoring :recycle:

#731 User management
  apps/web/src/app/(admin)/admin/brukere/action.ts
  apps/web/src/app/(admin)/admin/brukere/columns.tsx
  apps/web/src/app/(admin)/admin/brukere/schemas.ts
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/components/ui/form.tsx
  apps/web/src/components/ui/switch.tsx
  packages/lib/src/constants.ts
Labels: feature :sparkles:

#786 Update seed
  packages/db/drizzle/seed.ts
Labels: manual work :muscle:

#787 Semi dashboard for grupper og happenings
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  apps/web/src/app/(admin)/admin/happenings/page.tsx
  apps/web/src/app/(admin)/admin/sidebar.tsx
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  packages/db/schemas/groups.ts
Labels: feature :sparkles:

#789 Remove prose from markdown
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/components/markdown.tsx
  apps/web/src/components/post-preview.tsx
  apps/web/src/lib/is-board.ts
  apps/web/src/sanity/posts/index.ts
Labels: design 💄

#808 404 page
  apps/web/src/app/layout.tsx
  apps/web/src/app/not-found.tsx
  apps/web/tailwind.config.ts
Labels: feature :sparkles:

#809 Road to design system
  apps/web/src/app/(admin)/admin/brukere/page.tsx
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  apps/web/src/app/(admin)/admin/happenings/page.tsx
  apps/web/src/app/(admin)/admin/page.tsx
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
  apps/web/src/app/(default)/[type]/[slug]/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/event-sidebar.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/auth/logg-inn/sign-in-buttons.tsx
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/bedpres-sidebar.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/jobber/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/app/(default)/tilbakemelding/page.tsx
  apps/web/src/app/(default)/typography/page.tsx
  apps/web/src/app/(default)/webkom/page.tsx
  apps/web/src/app/not-found.tsx
  apps/web/src/components/feedback-blob.tsx
  apps/web/src/components/markdown.tsx
  apps/web/src/components/typography/blockquote.tsx
  apps/web/src/components/typography/callout.tsx
  apps/web/src/components/typography/chip.tsx
  apps/web/src/components/typography/heading.tsx
  apps/web/src/components/typography/list-item.tsx
  apps/web/src/components/typography/list.tsx
  apps/web/src/components/typography/text.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/components/ui/heading.tsx
  apps/web/src/styles/globals.css
  apps/web/tailwind.config.ts
  turbo.json
Labels: design 💄

#824 Upgrade next
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/app/api/auth/[...nextauth]/route.ts
  packages/auth/package.json
  packages/auth/src/auth-options.ts
  packages/auth/src/drizzle-adapter.ts
  packages/db/package.json
  packages/db/schemas/accounts.ts
  packages/eslint/package.json
  pnpm-lock.yaml
Labels: build 🔧

#830 Fix verify echo member
  apps/web/next.config.mjs
  apps/web/src/actions/feedback.ts
  apps/web/src/actions/register.ts
  apps/web/src/actions/verify-feide.ts
  apps/web/src/app/(default)/arrangement/[slug]/event-sidebar.tsx
  apps/web/src/app/(default)/auth/logg-inn/page.tsx
  apps/web/src/app/(default)/auth/logg-inn/sign-in-buttons.tsx
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/app/(default)/auth/profil/verify-button.tsx
  apps/web/src/app/(default)/bedpres/[slug]/bedpres-sidebar.tsx
  apps/web/src/app/(default)/tilbakemelding/feedback-form.tsx
  apps/web/src/app/(default)/tilbakemelding/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/components/ui/form.tsx
  apps/web/src/components/ui/input.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/ui/textarea.tsx
  apps/web/src/components/ui/toast.tsx
  apps/web/src/lib/is-valid-verified.test.ts
  apps/web/src/lib/is-valid-verified.ts
  apps/web/src/lib/schemas/feedback.ts
  packages/auth/src/auth-options.ts
  packages/auth/src/feide.ts
  packages/auth/src/is-member-of-echo.ts
  packages/db/drizzle/migrations/0002_tricky_marvel_zombies.sql
  packages/db/drizzle/migrations/0003_ordinary_red_ghost.sql
  packages/db/drizzle/migrations/meta/0002_snapshot.json
  packages/db/drizzle/migrations/meta/0003_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/enums.ts
  packages/db/schemas/site-feedback.ts
  packages/db/schemas/users.ts
  playwright/package.json
  playwright/playwright.config.ts
  playwright/web/feedback.spec.ts
Labels: feature :sparkles:

#844 Deactivate preview db workflow
  .github/workflows/destroy-preview.yaml
  .github/workflows/preview.yaml
Labels: build 🔧

#848 Endre type fra 'event' til 'arrangement'
  apps/web/src/components/event-filter.tsx
Labels: bug :bug:
