Repository echo-webkom/echo-web-mono, pull requests merged in 2023-04, with the labels that each got.

#91 Update gitignore
  .gitignore
Labels: manual work :muscle:

#117 Add documentation
  README.md
  apps/docs/docs/backend/index.md
  apps/docs/docs/backend/teknologier.md
  apps/docs/docs/backend/trpc.md
  apps/docs/docs/hvordan-starte.md
  apps/docs/docs/komme-igang/_category_.json
  apps/docs/docs/komme-igang/index.md
  apps/docs/docs/komme-igang/platformer.md
  apps/docs/docs/komme-igang/verktoy.md
  apps/docs/docs/sanity/dokumenter.md
  apps/docs/docs/sanity/groq.md
  apps/docs/docs/sanity/index.md
  apps/docs/docs/sanity/teknologier.md
  apps/docs/docusaurus.config.js
Labels: documentation :memo:

#122 Update renovate config
  .github/renovate.json
Labels: manual work :muscle:

#136 Decode basic auth password
  apps/web/src/middleware.ts
  tests/package.json
  tests/web/sanity.spec.ts
Labels: bug :bug:, testing :test_tube:

#137 Fix prisma no exported member
  packages/db/prisma/schema.prisma
Labels: bug :bug:, build 🔧

#141 Update student group page
  apps/cms/schemas/profile.tsx
  apps/cms/schemas/student-group.tsx
  apps/web/src/api/profile/schemas.ts
  apps/web/src/api/student-group/index.ts
  apps/web/src/api/student-group/schemas.ts
  apps/web/src/api/utils/image.ts
  apps/web/src/pages/for-students/[type].tsx
  apps/web/src/pages/for-students/group/[slug].tsx
  apps/web/src/pages/index.tsx
Labels: refactoring :recycle:, design 💄

#142 Option for custom separator in breadcrumbs
  apps/web/src/components/ui/breadcrumbs.tsx
Labels: feature :sparkles:

#153 Update turbo script and add title to code blocks in docs
  apps/cms/package.json
  apps/docs/docs/backend/trpc.md
  apps/docs/docs/sanity/dokumenter.md
  apps/docs/docs/sanity/groq.md
  package.json
  tests/package.json
  turbo.json
Labels: documentation :memo:, refactoring :recycle:

#174 Webkom spinner/loader
  apps/web/public/gif/webkom-loading.gif
  apps/web/src/components/page-loader.tsx
  apps/web/src/pages/auth/profile.tsx
Labels: feature :sparkles:

#164 Update tailwind config
  .eslintrc.js
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/components/banner.tsx
  apps/web/src/components/bedpres-preview.tsx
  apps/web/src/components/container.tsx
  apps/web/src/components/event-preview.tsx
  apps/web/src/components/feedback.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/header-logo.tsx
  apps/web/src/components/header.tsx
  apps/web/src/components/jobad-preview.tsx
  apps/web/src/components/navigation.tsx
  apps/web/src/components/ui/accordion.tsx
  apps/web/src/components/ui/avatar.tsx
  apps/web/src/components/ui/breadcrumbs.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/components/ui/dialog.tsx
  apps/web/src/components/ui/input.tsx
  apps/web/src/components/ui/label.tsx
  apps/web/src/components/ui/radio-group.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/ui/textarea.tsx
  apps/web/src/components/ui/toast.tsx
  apps/web/src/components/user-form.tsx
  apps/web/src/hooks/use-mouse-position.tsx
  apps/web/src/layouts/layout.tsx
  apps/web/src/lib/routes.ts
  apps/web/src/pages/404.tsx
  apps/web/src/pages/auth/profile.tsx
  apps/web/src/pages/auth/sign-in.tsx
  apps/web/src/pages/auth/sign-out.tsx
  apps/web/src/pages/event/[slug].tsx
  apps/web/src/pages/for-students/[groupType].tsx
  apps/web/src/pages/for-students/job/[slug].tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/globals.css
  apps/web/src/utils/cn.ts
  apps/web/tailwind.config.ts
  packages/config/tailwind/index.js
  packages/config/tailwind/index.ts
  packages/config/tailwind/package.json
  packages/config/tailwind/tsconfig.json
  pnpm-lock.yaml
  prettier.config.cjs
Labels: manual work :muscle:, refactoring :recycle:, design 💄

#187 Remove i18n
  apps/cms/schemas/bedpres.tsx
  apps/cms/schemas/event.tsx
  apps/cms/schemas/index.ts
  apps/cms/schemas/job-ad.tsx
  apps/cms/schemas/objects/locale.tsx
  apps/cms/schemas/post.tsx
  apps/cms/schemas/static-info.tsx
  apps/cms/schemas/student-group.tsx
  apps/web/src/api/bedpres/index.ts
  apps/web/src/api/bedpres/schemas.ts
  apps/web/src/api/event/index.ts
  apps/web/src/api/event/schemas.ts
  apps/web/src/api/job-ad/index.ts
  apps/web/src/api/job-ad/schemas.ts
  apps/web/src/api/posts/index.ts
  apps/web/src/api/posts/schemas.ts
  apps/web/src/api/static-info/index.ts
  apps/web/src/api/static-info/schemas.ts
  apps/web/src/api/student-group/index.ts
  apps/web/src/api/student-group/schemas.ts
  apps/web/src/api/utils/locale.ts
  apps/web/src/components/student-group-page.tsx
  apps/web/src/pages/[slug].tsx
  apps/web/src/pages/bedpres/[slug].tsx
  apps/web/src/pages/event/[slug].tsx
  apps/web/src/pages/for-students/[groupType].tsx
  apps/web/src/pages/for-students/group/[slug].tsx
  apps/web/src/pages/for-students/job/[slug].tsx
  apps/web/src/pages/for-students/post/[slug].tsx
  apps/web/src/pages/for-students/post/index.tsx
  apps/web/src/pages/index.tsx
Labels: refactoring :recycle:

#189 Add site settings in sanity
  apps/cms/sanity.config.ts
  apps/cms/schemas/index.ts
  apps/cms/schemas/objects/banner.tsx
  apps/cms/schemas/site-settings.tsx
  apps/cms/src/desk-structure.ts
  apps/web/src/api/banner/index.ts
  apps/web/src/api/settings/index.ts
  apps/web/src/api/settings/schemas.ts
  apps/web/src/components/banner.tsx
  apps/web/src/components/header.tsx
Labels: refactoring :recycle:

#188 Use sanity image builder
  apps/web/src/api/bedpres/index.ts
  apps/web/src/api/bedpres/schemas.ts
  apps/web/src/api/company/schemas.ts
  apps/web/src/api/job-ad/index.ts
  apps/web/src/api/job-ad/schemas.ts
  apps/web/src/api/posts/index.ts
  apps/web/src/api/posts/schemas.ts
  apps/web/src/api/profile/schemas.ts
  apps/web/src/api/student-group/index.ts
  apps/web/src/api/student-group/schemas.ts
  apps/web/src/components/bedpres-preview.tsx
  apps/web/src/components/jobad-preview.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/pages/for-students/group/[slug].tsx
  apps/web/src/pages/for-students/job/[slug].tsx
  apps/web/src/pages/for-students/job/index.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/webkom.tsx
Labels: refactoring :recycle:

#197 Add gif for no event
  apps/web/public/gif/empty-shelves-john-travolta.gif
  apps/web/public/gif/fresh-prince-room.gif
  apps/web/src/pages/index.tsx
Labels: feature :sparkles:

#198 Header redesign
  apps/web/src/components/feedback.tsx
  apps/web/src/components/header.tsx
  apps/web/src/components/navigation.tsx
  apps/web/src/components/tailwind-indicator.tsx
  apps/web/src/lib/routes.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/styles/globals.css
Labels: feature :sparkles:

#201 Fix header overlay above banner
  apps/web/src/components/banner.tsx
  apps/web/src/components/header.tsx
Labels: refactoring :recycle:

#190 Add more docs
  apps/docs/docs/cicd/index.md
  apps/docs/docs/frontend/framer-motion.md
  apps/docs/docs/frontend/react.md
  apps/docs/docs/frontend/tailwind.md
  apps/docs/docs/frontend/teknologier.md
  apps/docs/docs/frontend/typescript.md
  apps/docs/docs/komme-igang/forste-endring.md
  apps/docs/docs/komme-igang/verktoy.md
  apps/docs/docs/ressurser.md
  apps/docs/src/pages/index.tsx
Labels: documentation :memo:

#202 Add feedback tooltip
  apps/web/package.json
  apps/web/src/components/feedback.tsx
  apps/web/src/components/ui/tooltip.tsx
  pnpm-lock.yaml
Labels: design 💄

#203 Add profile icon
  apps/web/package.json
  apps/web/src/components/header.tsx
  apps/web/src/components/profile-icon.tsx
  apps/web/src/components/ui/dropdown-menu.tsx
  apps/web/src/pages/auth/sign-out.tsx
  packages/auth/src/auth-options.ts
  pnpm-lock.yaml
Labels: feature :sparkles:

#184 Add admin pages
  README.md
  apps/cms/schemas/bedpres.tsx
  apps/docs/docs/backend/trpc.md
  apps/docs/docs/ressurser.md
  apps/web/src/components/header.tsx
  apps/web/src/components/spotlight-card.tsx
  apps/web/src/components/student-group-page.tsx
  apps/web/src/components/ui/dialog.tsx
  apps/web/src/components/user-form.tsx
  apps/web/src/layouts/admin.tsx
  apps/web/src/layouts/default.tsx
  apps/web/src/lib/checks/with-admin-auth.tsx
  apps/web/src/lib/routes.ts
  apps/web/src/pages/404.tsx
  apps/web/src/pages/[slug].tsx
  apps/web/src/pages/admin/feedback.tsx
  apps/web/src/pages/admin/index.tsx
  apps/web/src/pages/admin/users.tsx
  apps/web/src/pages/auth/profile.tsx
  apps/web/src/pages/auth/sign-in.tsx
  apps/web/src/pages/bedpres/[slug].tsx
  apps/web/src/pages/event/[slug].tsx
  apps/web/src/pages/for-students/[groupType].tsx
  apps/web/src/pages/for-students/group/[slug].tsx
  apps/web/src/pages/for-students/job/[slug].tsx
  apps/web/src/pages/for-students/job/index.tsx
  apps/web/src/pages/for-students/post/[slug].tsx
  apps/web/src/pages/for-students/post/index.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/minutes/[slug].tsx
  apps/web/src/pages/minutes/index.tsx
  apps/web/src/pages/webkom.tsx
  packages/api/src/root.ts
  packages/api/src/routers/feedback.ts
  packages/api/src/routers/user.ts
  packages/api/src/trpc.ts
  packages/db/prisma/schema.prisma
Labels: feature :sparkles:
