Repository echo-webkom/echo-web-mono, pull requests merged in 2023-09, with the labels that each got.

#641 Remove docs banner
  apps/docs/theme.config.tsx
  apps/web/next.config.mjs
Labels: design 💄

#642 Fix typo
  apps/docs/src/pages/docs/komme-igang/setup-git.mdx
Labels: manual work :muscle:

#644 Adda navne mitt!
  apps/web/src/app/(default)/webkom/page.tsx
Labels: manual work :muscle:

#651 Add setup command
  package.json
Labels: build 🔧

#251 Preview database
  .github/workflows/ci.yaml
  .github/workflows/destroy-preview.yaml
  .github/workflows/preview.yaml
  .gitignore
  packages/db/docker-compose.yaml
  terraform/main/.terraform.lock.hcl
  terraform/main/main.tf
  terraform/main/outputs.tf
  terraform/main/variables.tf
  terraform/preview/.terraform.lock.hcl
  terraform/preview/main.tf
  terraform/preview/outputs.tf
  terraform/preview/variables.tf
Labels: feature :sparkles:

#671 Update delete db workflow
  .github/workflows/destroy-preview.yaml
  .github/workflows/preview.yaml
Labels: ci 🔄

#672 Rename to norwegian routes
  README.md
  apps/cms/schemas/event.tsx
  apps/docs/src/pages/docs/komme-igang/forste-endring.mdx
  apps/docs/src/pages/docs/komme-igang/scripts.mdx
  apps/web/package.json
  apps/web/src/app/(admin)/admin/brukere/columns.tsx
  apps/web/src/app/(admin)/admin/brukere/data-table.tsx
  apps/web/src/app/(admin)/admin/brukere/page.tsx
  apps/web/src/app/(admin)/admin/sidebar.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/auth/logg-inn/page.tsx
  apps/web/src/app/(default)/auth/logg-inn/sign-in-buttons.tsx
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/error.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/layout.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/event/[slug]/error.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/jobber/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/app/(default)/layout.tsx
  apps/web/src/app/(landing)/content.tsx
  apps/web/src/app/(landing)/page.tsx
  apps/web/src/app/not-found.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/job-ad-preview.tsx
  apps/web/src/components/post-preview.tsx
  apps/web/src/components/profile-icon.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/student-group-preview.tsx
  apps/web/src/lib/route-builder.ts
  apps/web/src/lib/routes.ts
  apps/web/src/sanity/static-info/index.ts
  apps/web/src/sanity/student-group/index.ts
  package.json
  packages/auth/src/auth-options.ts
  packages/db/docker-compose.yaml
  packages/db/package.json
  pnpm-lock.yaml
Labels: refactoring :recycle:
