Repository echo-webkom/echo-web-mono, pull requests merged in 2024-06, with the labels that each got.

#1984 Fix unban API
  apps/web/src/lib/ban-info.ts
Labels: bug :bug:

#2017 Bump turbo
  package.json
  packages/config/eslint/package.json
  pnpm-lock.yaml
  turbo.json
Labels: dependencies :handshake:

#2040 New log in page
  apps/web/src/app/(default)/auth/logg-inn/sign-in-buttons.tsx
  apps/web/src/assets/svg/sanity-logo.svg
  apps/web/src/assets/svg/vercel-logotype-dark.svg
  apps/web/src/assets/svg/vercel-logotype-light.svg
  apps/web/src/components/icons/feide.tsx
  apps/web/src/components/markdown.tsx
  apps/web/src/components/typography/heading.tsx
  apps/web/src/styles/globals.css
  apps/web/src/utils/generate-id.ts
  apps/web/tailwind.config.ts
  pnpm-lock.yaml
Labels: feature :sparkles:, design 💄

#2048 Fix bento
  apps/web/src/app/(default)/hjem/page.tsx
  apps/web/src/assets/images/happy-boss.png
  apps/web/src/assets/images/happy-students.png
  apps/web/src/components/calendar/happening-calendar.tsx
  apps/web/src/components/movie-club-card.tsx
Labels: bug :bug:

#2053 Various minor style changes
  apps/web/src/components/calendar/happening-calendar.tsx
  apps/web/src/components/event-page.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/sidebar.tsx
  apps/web/src/components/typography/text.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/styles/globals.css
  apps/web/tailwind.config.ts
Labels: design 💄
