Repository echo-webkom/echo-web-mono, pull requests merged in 2024-03, with the labels that each got.

#1533 Remove banner
  apps/web/src/app/(default)/page.tsx
Labels: manual work :muscle:

#1538 Remove unused dependencies
  apps/web/package.json
  package.json
  packages/lib/package.json
  pnpm-lock.yaml
Labels: dependencies :handshake:

#1543 Animate rainbow colors
  apps/web/src/app/(default)/page.tsx
  apps/web/src/styles/globals.css
Labels: design 💄

#1542 Fetch bylaws from repo
  apps/web/src/app/(default)/om/vedtekter/page.tsx
Labels: feature :sparkles:

#1537 Add rss feed endpoint
  apps/web/src/app/feed/route.ts
Labels: feature :sparkles:

#1544 Fix broken links
  apps/web/next.config.mjs
  apps/web/src/app/feed/route.ts
Labels: bug :bug:

#1546 Implement boomtown
  apps/web/src/actions/deregister.ts
  apps/web/src/actions/register.ts
  apps/web/src/api/boomtown.ts
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/registration-count.tsx
  apps/web/src/hooks/use-registrations.ts
  turbo.json
Labels: feature :sparkles:

#1548 Better ws
  apps/web/src/hooks/use-registrations.ts
Labels: bug :bug:

#1549 lol
  apps/web/package.json
  apps/web/src/hooks/use-registrations.ts
  pnpm-lock.yaml
Labels: bug :bug:

#1550 Add registrations progress bar
  apps/web/src/components/registration-count.tsx
Labels: feature :sparkles:

#1551 Fix progress bar
  apps/web/src/components/registration-count.tsx
Labels: feature :sparkles:

#1552 Animate progress bar
  apps/web/src/components/registration-count.tsx
Labels: design 💄

#1555 Dashboard for strikes
  apps/web/src/app/(default)/prikker/dashboard/page.tsx
  apps/web/src/app/(default)/prikker/layout.tsx
  apps/web/src/app/(default)/prikker/page.tsx
  apps/web/src/app/(default)/prikker/table.tsx
  apps/web/src/data/strikes/queries.ts
  apps/web/src/data/strikes/revalidate.ts
Labels: feature :sparkles:

#1566 Add and remove strikes
  apps/web/src/actions/strikes.ts
  apps/web/src/app/(default)/prikker/[userId]/page.tsx
  apps/web/src/app/(default)/prikker/[userId]/strike-button.tsx
  apps/web/src/data/happenings/queries.ts
  apps/web/src/data/strikes/mutations.ts
  apps/web/src/data/strikes/queries.ts
  apps/web/src/data/strikes/revalidate.ts
  apps/web/src/lib/schemas/addStrike.ts
  apps/web/src/utils/list.ts
  packages/db/drizzle/seed.ts
  packages/lib/src/constants.ts
  playwright/web/strikes.spec.ts
Labels: feature :sparkles:

#1584 Fix link wrap
  apps/web/src/components/typography/text.tsx
Labels: bug :bug:

#1585 Fix lint error
  apps/web/src/app/(default)/auth/profil/arrangementer/page.tsx
Labels: ci 🔄

#1530 Zeno/filmklubbkort
  apps/cms/schemas/index.ts
  apps/cms/schemas/movies.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/components/movie-club-card.tsx
  apps/web/src/sanity/movies/index.ts
  apps/web/src/sanity/movies/queries.ts
  apps/web/src/sanity/movies/requests.ts
  apps/web/src/sanity/movies/schemas.ts
Labels: feature :sparkles:, design 💄

#1588 Fix typecheck
  apps/web/src/sanity/movies/schemas.ts
Labels: bug :bug:

#1589 Revalidate movies
  apps/web/src/app/api/sanity/revalidate/route.ts
  apps/web/src/sanity/movies/requests.ts
Labels: feature :sparkles:

#1591 Increase to 5 events and bedpresses
  apps/web/src/app/(default)/content.tsx
Labels: feature :sparkles:

#1593 Remove banner
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:

#1595 Include movies in calendar
  apps/web/src/app/(default)/beta/calendar/page.tsx
  apps/web/src/app/api/calendar/route.ts
  apps/web/src/sanity/movies/requests.ts
Labels: feature :sparkles:

#1596 Add calendar url builder
  apps/web/src/app/(default)/beta/calendar/page.tsx
  apps/web/src/app/api/calendar/route.ts
  apps/web/src/lib/calendar-url-builder.ts
Labels: feature :sparkles:

#1597 Add bedpres registration to calendar
  apps/web/src/app/(default)/beta/calendar/page.tsx
  apps/web/src/app/api/calendar/route.ts
  apps/web/src/lib/calendar-url-builder.ts
Labels: feature :sparkles:

#1235 Add happening calendar
  apps/web/package.json
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/components/calendar/happening-calendar.tsx
  apps/web/src/components/ui/hover-card.tsx
  apps/web/src/lib/create-link.ts
  apps/web/src/utils/date.ts
  pnpm-lock.yaml
Labels: feature :sparkles:

#1564 Add PWA
  apps/web/.gitignore
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/public/site.webmanifest
  apps/web/src/manifest.json
  apps/web/src/sw.ts
  apps/web/tsconfig.json
  pnpm-lock.yaml
Labels: feature :sparkles:

#1619 Remove sw
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/public/site.webmanifest
  apps/web/src/sw.ts
  apps/web/tsconfig.json
  pnpm-lock.yaml
Labels: bug :bug:

#1617 Handle bans
  apps/web/src/actions/strikes.ts
  apps/web/src/app/(default)/prikker/[userId]/page.tsx
  apps/web/src/app/(default)/prikker/[userId]/strike-button.tsx
  apps/web/src/data/happenings/queries.ts
  apps/web/src/data/users/mutations.ts
  apps/web/src/lib/ban-info.ts
Labels: feature :sparkles:

#1624 Add seeder
  .github/workflows/ci.yaml
  apps/cms/package.json
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(redirects)/event/[slug]/page.tsx
  apps/web/src/app/(redirects)/sanity/route.ts
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/components/post-preview.tsx
  package.json
  packages/auth/package.json
  packages/db/drizzle/seed.ts
  packages/db/package.json
  packages/echogram/package.json
  packages/email/package.json
  packages/eslint/package.json
  packages/lib/package.json
  packages/lib/src/__tests__/is-board.test.ts
  packages/lib/src/index.ts
  packages/lib/src/is-board.ts
  packages/seeder/package.json
  packages/seeder/src/db/data/degrees.ts
  packages/seeder/src/db/data/groups.ts
  packages/seeder/src/db/data/users.ts
  packages/seeder/src/db/index.ts
  packages/seeder/src/db/repo/happening.ts
  packages/seeder/src/db/repo/user.ts
  packages/seeder/src/index.ts
  packages/seeder/src/sanity/client.ts
  packages/seeder/src/sanity/index.ts
  packages/seeder/src/sanity/query.ts
  packages/seeder/tsconfig.json
  playwright/package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: feature :sparkles:

#1628 Move echogram
  apps/web/src/actions/images.ts
  apps/web/src/api/echogram.ts
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/app/api/images/route.ts
  apps/web/src/lib/echogram.ts
  packages/echogram/package.json
  packages/echogram/tsconfig.json
Labels: refactoring :recycle:

#1637 Prikker / bans
  apps/web/src/actions/register.ts
  apps/web/src/actions/strikes.ts
  apps/web/src/app/(default)/auth/profil/layout.tsx
  apps/web/src/app/(default)/auth/profil/prikker/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/prikker/[userId]/page.tsx
  apps/web/src/app/(default)/prikker/layout.tsx
  apps/web/src/app/api/unban/route.ts
  apps/web/src/components/edit-registration-button.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/registration-table.tsx
  apps/web/src/components/user-menu.tsx
  apps/web/src/data/happenings/queries.ts
  apps/web/src/data/strikes/queries.ts
  apps/web/src/data/users/queries.ts
  apps/web/src/lib/ban-info.ts
  apps/web/src/lib/memberships.ts
Labels: feature :sparkles:

#1607 Add kaffe api client
  apps/web/src/actions/kaffe-strikes.ts
  apps/web/src/api/boomtown.ts
  apps/web/src/api/kaffe.ts
  apps/web/src/app/(default)/kaffe/StrikeButtons.tsx
  apps/web/src/app/(default)/kaffe/page.tsx
  turbo.json
Labels: feature :sparkles:

#1644 Fix images
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/components/calendar/happening-calendar.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/lib/create-link.ts
Labels: design 💄

#1646 Display movies in calendar
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/components/calendar/happening-calendar.tsx
  apps/web/src/sanity/movies/queries.ts
  apps/web/src/sanity/movies/schemas.ts
Labels: feature :sparkles:

#1586 Create tsconfig package
  apps/cms/package.json
  apps/cms/tsconfig.json
  apps/web/package.json
  apps/web/src/app/api/images/route.ts
  apps/web/tsconfig.json
  packages/auth/package.json
  packages/auth/tsconfig.json
  packages/config/eslint/base.js
  packages/config/eslint/nextjs.js
  packages/config/eslint/package.json
  packages/config/eslint/react.js
  packages/config/tsconfig/base.json
  packages/config/tsconfig/nextjs.json
  packages/config/tsconfig/package.json
  packages/config/tsconfig/react.json
  packages/db/package.json
  packages/db/tsconfig.json
  packages/email/package.json
  packages/email/tsconfig.json
  packages/lib/package.json
  packages/lib/tsconfig.json
  packages/seeder/package.json
  packages/seeder/tsconfig.json
  playwright/package.json
  playwright/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
  turbo.json
Labels: build 🔧

#1649 Decrease num happenings
  apps/web/src/app/(default)/content.tsx
  turbo.json
Labels: refactoring :recycle:

#1652 Optimize happening sidebar
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/registration-count.tsx
Labels: refactoring :recycle:

#1655 Quix fix prikker
  apps/web/src/app/(default)/prikker/[userId]/page.tsx
  apps/web/src/app/(default)/prikker/layout.tsx
  apps/web/src/data/happenings/queries.ts
Labels: bug :bug:

#1659 Make frontpage faster
  apps/web/src/app/(default)/_components/happening-preview.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/lib/is-bedpres.ts
Labels: refactoring :recycle:

#1661 Frontpage cdn
  apps/web/src/app/(default)/page.tsx
  apps/web/src/sanity/client.ts
  apps/web/src/sanity/happening/requests.ts
  apps/web/src/sanity/job-ad/requests.ts
  apps/web/src/sanity/posts/requests.ts
Labels: refactoring :recycle:

#1663 Add auth check in page
  apps/web/src/app/(admin)/admin/brukere/page.tsx
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  apps/web/src/app/(admin)/admin/happenings/page.tsx
  apps/web/src/app/(admin)/admin/layout.tsx
  apps/web/src/app/(admin)/admin/page.tsx
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
  apps/web/src/app/(admin)/admin/whitelist/page.tsx
  apps/web/src/lib/ensure.ts
Labels: feature :sparkles:, refactoring :recycle:

#1680 Remove terraform
  terraform/main/outputs.tf
  terraform/main/variables.tf
  terraform/preview/outputs.tf
  terraform/preview/variables.tf
Labels: refactoring :recycle:

#1648 Add seed cli
  .env.example
  .github/workflows/ci.yaml
  README.md
  apps/cms/schemas/happening.tsx
  apps/cms/schemas/objects/question.tsx
  apps/web/package.json
  apps/web/src/actions/deregister.ts
  apps/web/src/app/(default)/_components/happening-preview.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/components/happening-preview-box.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/job-ad-preview.tsx
  apps/web/src/components/job-ad-sidebar.tsx
  apps/web/src/components/movie-club-card.tsx
  apps/web/src/sanity/client.ts
  apps/web/src/sanity/utils/contacts.ts
  apps/web/src/utils/image-builder.ts
  packages/lib/src/constants.ts
  packages/sanity/package.json
  packages/sanity/src/index.ts
  packages/sanity/tsconfig.json
  packages/seeder/README.md
  packages/seeder/package.json
  packages/seeder/src/db/index.ts
  packages/seeder/src/db/mode.ts
  packages/seeder/src/index.ts
  packages/seeder/src/sanity/client.ts
  packages/seeder/src/sanity/index.ts
  packages/seeder/src/sanity/query.ts
  packages/seeder/src/sanity/utils.ts
  packages/seeder/src/utils.ts
  pnpm-lock.yaml
  turbo.json
Labels: feature :sparkles:, refactoring :recycle:, testing :test_tube:

#1702 Add zod to db package
  packages/db/package.json
  pnpm-lock.yaml
Labels: dependencies :handshake:

#1704 Remove typecasting
  packages/seeder/src/db/mode.ts
Labels: refactoring :recycle:

#1710 Add admin UI
  apps/web/src/actions/degree.ts
  apps/web/src/actions/feedback.ts
  apps/web/src/actions/groups.ts
  apps/web/src/actions/kaffe-strikes.ts
  apps/web/src/actions/update-registration.ts
  apps/web/src/actions/user.ts
  apps/web/src/app/(admin)/admin/grupper/_components/add-group-button.tsx
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  apps/web/src/app/(admin)/admin/happenings/page.tsx
  apps/web/src/app/(admin)/admin/studieretninger/_components/add-degree-button.tsx
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/_components/feedback.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
  apps/web/src/app/(admin)/admin/whitelist/page.tsx
  apps/web/src/app/(default)/tilbakemelding/feedback-form.tsx
  apps/web/src/data/degrees/mutations.ts
  apps/web/src/data/degrees/queries.ts
  apps/web/src/data/degrees/revalidate.ts
  apps/web/src/data/groups/mutations.ts
  apps/web/src/data/groups/queries.ts
  apps/web/src/data/groups/revalidate.ts
  apps/web/src/data/site-feedbacks/mutations.ts
  apps/web/src/data/site-feedbacks/queries.ts
  apps/web/src/lib/ensure.ts
  apps/web/src/lib/schemas/add-degree.ts
  apps/web/src/lib/schemas/add-group.ts
  packages/auth/src/helpers.ts
Labels: feature :sparkles:

#1715 Improve logging
  apps/web/package.json
  apps/web/src/app/(default)/[...slug]/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/data/reactions/queries.ts
  apps/web/src/data/registrations/queries.ts
  apps/web/src/data/shopping-list-item/queries.ts
  apps/web/src/data/spotrange/queries.ts
  apps/web/src/lib/logger.ts
  apps/web/src/sanity/happening/requests.ts
  apps/web/src/sanity/job-ad/requests.ts
  apps/web/src/sanity/minutes/requests.ts
  apps/web/src/sanity/posts/requests.ts
  pnpm-lock.yaml
Labels: feature :sparkles:
