Repository echo-webkom/echo-web-mono, pull requests merged in 2024-02, with the labels that each got.

#1347 Remove docs from mono
  apps/docs/next.config.mjs
  apps/docs/package.json
  apps/docs/postcss.config.cjs
  apps/docs/public/android-chrome-192x192.png
  apps/docs/public/android-chrome-512x512.png
  apps/docs/public/apple-touch-icon.png
  apps/docs/public/browserconfig.xml
  apps/docs/public/favicon-16x16.png
  apps/docs/public/favicon-32x32.png
  apps/docs/public/favicon.ico
  apps/docs/public/favicon.png
  apps/docs/public/images/webkom.png
  apps/docs/public/mstile-150x150.png
  apps/docs/public/safari-pinned-tab.svg
  apps/docs/public/site.webmanifest
  apps/docs/src/components/code-example.tsx
  apps/docs/src/components/cool-component.tsx
  apps/docs/src/components/landing-page.tsx
  apps/docs/src/pages/_app.mdx
  apps/docs/src/pages/_meta.json
  apps/docs/src/pages/docs/_meta.json
  apps/docs/src/pages/docs/backend/_meta.json
  apps/docs/src/pages/docs/backend/auth.mdx
  apps/docs/src/pages/docs/backend/drizzle.mdx
  apps/docs/src/pages/docs/backend/index.mdx
  apps/docs/src/pages/docs/backend/nextjs.mdx
  apps/docs/src/pages/docs/cicd.mdx
  apps/docs/src/pages/docs/frontend/_meta.json
  apps/docs/src/pages/docs/frontend/framer-motion.mdx
  apps/docs/src/pages/docs/frontend/react.mdx
  apps/docs/src/pages/docs/frontend/tailwind.mdx
  apps/docs/src/pages/docs/frontend/typescript.mdx
  apps/docs/src/pages/docs/introduksjon.mdx
  apps/docs/src/pages/docs/komme-igang/_meta.json
  apps/docs/src/pages/docs/komme-igang/forste-endring.mdx
  apps/docs/src/pages/docs/komme-igang/platformer.mdx
  apps/docs/src/pages/docs/komme-igang/scripts.mdx
  apps/docs/src/pages/docs/komme-igang/setup-git.mdx
  apps/docs/src/pages/docs/komme-igang/verktoy.mdx
  apps/docs/src/pages/docs/ressurser.mdx
  apps/docs/src/pages/docs/sanity/_meta.json
  apps/docs/src/pages/docs/sanity/dokumenter.mdx
  apps/docs/src/pages/docs/sanity/felt-og-typer.mdx
  apps/docs/src/pages/docs/sanity/groq.mdx
  apps/docs/src/pages/docs/sanity/index.mdx
  apps/docs/src/pages/docs/sanity/objekter.mdx
  apps/docs/src/pages/index.mdx
  apps/docs/src/styles/globals.css
  apps/docs/tailwind.config.ts
  apps/docs/theme.config.tsx
  apps/docs/tsconfig.json
  apps/docs/vercel.json
  package.json
  playwright/docs/index.spec.ts
  playwright/playwright.config.ts
Labels: manual work :muscle:

#1350 Update lockfile
  pnpm-lock.yaml
Labels: build 🔧

#1353 Fix reaction buttons
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/reaction-button.tsx
  apps/web/src/styles/globals.css
  apps/web/tailwind.config.ts
Labels: work in progress 🚧, design 💄

#1357 Input blur on enter and add maxLenght
  apps/web/src/components/event-filter.tsx
Labels: refactoring :recycle:

#1260 Webhook for static content
  apps/web/src/app/api/sanity/revalidate/route.ts
Labels: feature :sparkles:

#1337 Add random word banner
  apps/web/src/components/site-header.tsx
  apps/web/src/components/theme-switch-button.tsx
  apps/web/src/lib/random-message.ts
Labels: feature :sparkles:

#1364 Fix request type
  apps/web/src/app/api/images/route.ts
Labels: bug :bug:

#1383 Fix optimistic type
  apps/web/src/components/reaction-button.tsx
Labels: bug :bug:

#1389 Fix webkom page
  apps/web/src/app/(default)/webkom/page.tsx
Labels: bug :bug:

#1395 Fix revalidate typo
  apps/web/src/app/api/sanity/revalidate/route.ts
Labels: bug :bug:

#1400 Redesign av job ad siden
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/components/job-ad-sidebar.tsx
Labels: feature :sparkles:, design 💄

#1316 Download ics
  apps/web/package.json
  apps/web/src/app/(default)/beta/calendar/page.tsx
  apps/web/src/app/api/calendar/route.ts
  pnpm-lock.yaml
Labels: feature :sparkles:

#1425 Add stricter calendar types
  apps/web/src/app/(default)/beta/calendar/page.tsx
Labels: bug :bug:

#1426 Add calendar name
  apps/web/src/app/api/calendar/route.ts
Labels: feature :sparkles:

#1427 Change iCal method to PUBLISH
  apps/web/src/app/api/calendar/route.ts
Labels: feature :sparkles:

#1432 Add logging to revalidate endpoint
  apps/web/src/app/api/sanity/revalidate/route.ts
Labels: feature :sparkles:

#1461 Zeno/årstrinn jobbannonse
  apps/web/package.json
  apps/web/src/components/job-ad-sidebar.tsx
  apps/web/src/lib/__tests__/degree-year.test.ts
  apps/web/src/lib/degree-year-text.ts
  apps/web/src/sanity/job-ad/schemas.ts
Labels: feature :sparkles:, design 💄

#1467 Update postgres
  packages/db/docker-compose.yaml
Labels: manual work :muscle:

#1473 Increase pool size
  packages/db/index.ts
Labels: feature :sparkles:

#1482 Set prepare to false
  apps/web/src/actions/register.ts
  packages/db/index.ts
Labels: feature :sparkles:

#1478 Update db with strikes
  packages/db/drizzle/migrations/0012_wide_vance_astro.sql
  packages/db/drizzle/migrations/meta/0012_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/index.ts
  packages/db/schemas/strike-infos.ts
  packages/db/schemas/strikes.ts
  packages/db/schemas/users.ts
Labels: feature :sparkles:

#1477 Add event job type
  apps/cms/schemas/job-ad.tsx
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/components/job-ad-preview.tsx
  apps/web/src/components/job-ad-sidebar.tsx
  apps/web/src/lib/__tests__/degree-year.test.ts
  apps/web/src/lib/degree-year-text.ts
  apps/web/src/sanity/job-ad/mappers.ts
  apps/web/src/sanity/job-ad/schemas.ts
  packages/lib/src/constants.ts
Labels: feature :sparkles:, refactoring :recycle:

#1494 Add ad job type
  packages/lib/src/constants.ts
Labels: feature :sparkles:

#1501 Add generalforsamling banner
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:

#1502 Add fork bomb message
  apps/web/src/lib/random-message.ts
Labels: feature :sparkles:

#1506 Fix register
  apps/web/src/actions/register.ts
Labels: bug :bug:

#1507 Revert "Fix register"
  apps/web/src/actions/register.ts
Labels: pls help :question:

#1509 Try fix register catch revert
  apps/web/src/actions/register.ts
  apps/web/src/components/deregister-button.tsx
  apps/web/src/components/happening-sidebar.tsx
  packages/db/drizzle/seed.ts
  scripts/add-to-group.sh
  scripts/get-id.sh
  scripts/register.sh
  scripts/revalidate.sh
  scripts/sync.sh
Labels: bug :bug:

#1512 Revalidate registrations on admin change
  apps/web/src/actions/update-registration.ts
Labels: bug :bug:
