Repository echo-webkom/echo-web-mono, pull requests merged in 2024-04, with the labels that each got.

#1737 Refactor RSS-feed
  apps/web/src/app/feed/route.ts
  apps/web/src/lib/calendar-url-builder.ts
  apps/web/src/lib/rss.ts
  apps/web/src/utils/__tests__/url.test.ts
  apps/web/src/utils/url.ts
Labels: refactoring :recycle:

#1731 Hermann/csv
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/api/registrations/route.ts
  apps/web/src/components/download-csv-button.tsx
  apps/web/src/components/registration-table.tsx
  apps/web/src/data/happenings/queries.ts
  apps/web/src/lib/__tests__/csv.test.ts
  apps/web/src/lib/csv.ts
Labels: feature :sparkles:, design 💄

#1739 omfj/axiom
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/actions/register.ts
  apps/web/src/app/(default)/[...slug]/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/api/auth/[...nextauth]/route.ts
  apps/web/src/app/api/sanity/revalidate/route.ts
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/app/api/unban/route.ts
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/data/reactions/queries.ts
  apps/web/src/data/registrations/queries.ts
  apps/web/src/data/shopping-list-item/queries.ts
  apps/web/src/data/spotrange/queries.ts
  apps/web/src/lib/logger.ts
  apps/web/src/sanity/happening/requests.ts
  apps/web/src/sanity/job-ad/requests.ts
  apps/web/src/sanity/minutes/requests.ts
  apps/web/src/sanity/posts/requests.ts
  pnpm-lock.yaml
Labels: feature :sparkles:, refactoring :recycle:

#1753 Prerender static content
  apps/web/public/favicon.png
  apps/web/public/favicon16x16.png
  apps/web/public/hero.jpg
  apps/web/src/app/(default)/[...path]/page.tsx
Labels: refactoring :recycle:

#1754 Prerender events
  apps/web/src/api/boomtown.ts
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/config.ts
  apps/web/src/sanity/happening/requests.ts
Labels: refactoring :recycle:

#1765 Fix page padding
  apps/web/src/app/(default)/[...path]/page.tsx
  apps/web/src/app/(default)/admin/brukere/page.tsx
  apps/web/src/app/(default)/admin/brukere/schemas.ts
  apps/web/src/app/(default)/admin/brukere/user-form.tsx
  apps/web/src/app/(default)/admin/grupper/_components/add-group-button.tsx
  apps/web/src/app/(default)/admin/grupper/members-modal.tsx
  apps/web/src/app/(default)/admin/grupper/page.tsx
  apps/web/src/app/(default)/admin/happenings/page.tsx
  apps/web/src/app/(default)/admin/layout.tsx
  apps/web/src/app/(default)/admin/loading.tsx
  apps/web/src/app/(default)/admin/page.tsx
  apps/web/src/app/(default)/admin/studieretninger/_components/add-degree-button.tsx
  apps/web/src/app/(default)/admin/studieretninger/page.tsx
  apps/web/src/app/(default)/admin/tilbakemeldinger/_components/feedback.tsx
  apps/web/src/app/(default)/admin/tilbakemeldinger/page.tsx
  apps/web/src/app/(default)/admin/whitelist/page.tsx
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/auth/logg-inn/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/beta/calendar/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
  apps/web/src/app/(default)/for-studenter/handleliste/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/jobber/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/app/(default)/gruppe/[id]/page.tsx
  apps/web/src/app/(default)/informasjonskapsler/page.tsx
  apps/web/src/app/(default)/kaffe/page.tsx
  apps/web/src/app/(default)/om/brosjyre/page.tsx
  apps/web/src/app/(default)/om/vedtekter/page.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/app/(default)/typography/page.tsx
  apps/web/src/app/(default)/webkom/page.tsx
Labels: design 💄

#1772 Optimize reg count
  apps/web/src/app/(default)/_components/happening-preview.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/config.ts
  apps/web/src/data/happenings/queries.ts
  apps/web/src/data/spotrange/queries.ts
  apps/web/src/lib/__tests__/get-spot-range-info.test.ts
  apps/web/src/lib/spot-range-info.ts
  packages/db/schemas/spot-ranges.ts
Labels: refactoring :recycle:

#1776 Optimize reg count 2
  apps/web/src/app/(default)/_components/happening-preview.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/config.ts
  apps/web/src/data/happenings/queries.ts
  apps/web/src/data/spotrange/queries.ts
  apps/web/src/lib/__tests__/get-spot-range-info.test.ts
  apps/web/src/lib/spot-range-info.ts
  packages/db/schemas/spot-ranges.ts
Labels: bug :bug:

#1759 Dashbord table
  apps/web/src/actions/strikes.ts
  apps/web/src/app/(default)/admin/brukere/page.tsx
  apps/web/src/app/(default)/admin/grupper/page.tsx
  apps/web/src/app/(default)/admin/studieretninger/page.tsx
  apps/web/src/app/(default)/admin/whitelist/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/prikker/[userId]/strike-button.tsx
  apps/web/src/components/registration-table.tsx
  apps/web/src/lib/csv.ts
  packages/email/emails/strike-notification.tsx
  packages/email/index.ts
Labels: feature :sparkles:

#1811 No upcoming happenings
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:

#1821 Hermann/prikk epost
  apps/web/src/actions/strikes.ts
  apps/web/src/components/registration-table.tsx
  apps/web/src/lib/csv.ts
Labels: bug :bug:

#1847 Fix infinite spots
  apps/web/src/actions/register.ts
Labels: bug :bug:
