Repository echo-webkom/echo-web-mono, pull requests merged in 2024-01, with the labels that each got.

#1098 Changing schema from nnumy1ga to pgq2pd26
  apps/cms/sanity.cli.ts
  apps/cms/sanity.config.ts
Labels: manual work :muscle:

#1099 Update project id
  apps/cms/package.json
  apps/web/src/sanity/client.ts
  apps/web/src/sanity/static-info/index.ts
  pnpm-lock.yaml
Labels: bug :bug:

#1103 Add redirects
  apps/web/next.config.mjs
  apps/web/src/app/(default)/event/[slug]/page.tsx
  apps/web/src/sanity/happening/index.ts
Labels: feature :sparkles:

#1105 Add more redirects
  apps/web/next.config.mjs
Labels: feature :sparkles:

#1106 Fix revalidate sanity
  apps/web/src/app/(default)/[...slug]/page.tsx
  apps/web/src/app/api/sanity/route.ts
Labels: bug :bug:

#1107 Fix redirect logic
  apps/web/src/sanity/happening/index.ts
Labels: bug :bug:

#1109 Minor changes
  apps/web/src/actions/register.ts
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:, refactoring :recycle:

#1111 Use track from server
  apps/web/src/actions/register.ts
Labels: feature :sparkles:

#1115 Add group admin page
  apps/docs/src/pages/docs/backend/auth.mdx
  apps/web/src/actions/deregister.ts
  apps/web/src/actions/register.ts
  apps/web/src/actions/update-registration.ts
  apps/web/src/actions/user.ts
  apps/web/src/actions/whitelist.ts
  apps/web/src/app/(admin)/admin/layout.tsx
  apps/web/src/app/(default)/auth/profil/arrangementer/page.tsx
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/app/(default)/gruppe/[id]/_components/add-user-to-group-dialog.tsx
  apps/web/src/app/(default)/gruppe/[id]/_components/group-user-form.tsx
  apps/web/src/app/(default)/gruppe/[id]/actions.ts
  apps/web/src/app/(default)/gruppe/[id]/page.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/site-header.tsx
  apps/web/src/components/ui/alert-dialog.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/lib/checks/with-session.ts
  apps/web/src/lib/schemas/add-user-to-group.ts
  packages/auth/src/helpers.ts
  packages/auth/src/index.ts
  pnpm-lock.yaml
Labels: feature :sparkles:

#1112 Remove leader reference
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  packages/db/drizzle/migrations/0004_soft_monster_badoon.sql
  packages/db/drizzle/migrations/meta/0004_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/groups.ts
Labels: refactoring :recycle:

#1119 Optimize images
  apps/web/src/assets/images/bekk.png
  apps/web/src/assets/images/echo-logo.png
  apps/web/src/assets/images/webkom.png
  apps/web/src/assets/svg/sanity-logo.svg
  apps/web/src/assets/svg/vercel-logotype-dark.svg
  apps/web/src/assets/svg/vercel-logotype-light.svg
  apps/web/src/components/footer.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/ui/header-logo.tsx
  apps/web/src/lib/sponsors.ts
Labels: bug :bug:, feature :sparkles:

#1124 Improve webhook endpoint
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/utils/date.ts
  apps/web/src/utils/list.ts
  packages/db/drizzle/migrations/0005_typical_ego.sql
  packages/db/drizzle/migrations/meta/0005_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/happenings-to-groups.ts
Labels: refactoring :recycle:

#1125 Make emails unique
  apps/web/src/app/(default)/gruppe/[id]/page.tsx
  packages/db/drizzle/migrations/0006_messy_gravity.sql
  packages/db/drizzle/migrations/meta/0006_snapshot.json
  packages/db/drizzle/migrations/meta/_journal.json
  packages/db/schemas/users.ts
Labels: bug :bug:

#1130 Track failed sign ins
  apps/web/src/app/api/auth/[...nextauth]/route.ts
  packages/auth/src/auth-options.ts
  packages/auth/src/helpers.ts
  packages/auth/src/index.ts
Labels: feature :sparkles:

#1126 Fix admin pages
  apps/web/src/app/(admin)/admin/grupper/page.tsx
  apps/web/src/app/(admin)/admin/happenings/page.tsx
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
  apps/web/src/lib/queries/feedback.ts
  apps/web/src/styles/globals.css
Labels: design 💄

#1132 Add revalidate script
  apps/web/src/app/api/revalidate/route.ts
  apps/web/src/app/api/sanity/revalidate/route.ts
  scripts/revalidate.sh
  scripts/update-happening.sh
Labels: feature :sparkles:

#1128 Prettier header
  .env.example
  apps/cms/env.d.ts
  apps/cms/package.json
  apps/cms/sanity.config.ts
  apps/cms/src/desk-structure.ts
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/components/mobile-navigation.tsx
  apps/web/src/lib/routes.ts
  pnpm-lock.yaml
Labels: design 💄

#1133 Refactor sanity package
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/event/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/components/banner.tsx
  apps/web/src/components/event-filter.tsx
  apps/web/src/components/happening-info-box.tsx
  apps/web/src/sanity/happening/index.ts
  apps/web/src/sanity/happening/queries.ts
  apps/web/src/sanity/happening/requests.ts
  apps/web/src/sanity/job-ad/index.ts
  apps/web/src/sanity/job-ad/mappers.ts
  apps/web/src/sanity/job-ad/queries.ts
  apps/web/src/sanity/job-ad/requests.ts
  apps/web/src/sanity/minutes/index.ts
  apps/web/src/sanity/minutes/queries.ts
  apps/web/src/sanity/minutes/requests.ts
  apps/web/src/sanity/minutes/schema.ts
  apps/web/src/sanity/posts/index.ts
  apps/web/src/sanity/posts/queries.ts
  apps/web/src/sanity/posts/requests.ts
  apps/web/src/sanity/profile/index.ts
  apps/web/src/sanity/settings/index.ts
  apps/web/src/sanity/settings/queries.ts
  apps/web/src/sanity/settings/requests.ts
  apps/web/src/sanity/static-info/index.ts
  apps/web/src/sanity/static-info/mappers.ts
  apps/web/src/sanity/static-info/queries.ts
  apps/web/src/sanity/static-info/requests.ts
  apps/web/src/sanity/student-group/index.ts
  apps/web/src/sanity/student-group/mappers.ts
  apps/web/src/sanity/student-group/queries.ts
  apps/web/src/sanity/student-group/requests.ts
  apps/web/src/sanity/student-group/schemas.ts
  packages/lib/src/index.ts
  packages/lib/src/mappers.ts
Labels: refactoring :recycle:

#1147 Dynamic post params
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/sanity/posts/requests.ts
Labels: feature :sparkles:

#1159 Downgrade sanity
  apps/cms/package.json
  pnpm-lock.yaml
Labels: dependencies :handshake:

#1161 Generate question id
  apps/cms/components/id-input.tsx
  apps/cms/package.json
  apps/cms/schemas/objects/question.tsx
  pnpm-lock.yaml
Labels: bug :bug:, feature :sparkles:

#1162 Add motereferater
  apps/web/src/lib/routes.ts
Labels: bug :bug:

#1163 Optimize
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
  apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
  apps/web/src/app/(default)/page.tsx
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/components/happening-info-box.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/registration-table.tsx
  apps/web/src/lib/initials.test.ts
  apps/web/src/lib/initials.ts
  apps/web/src/lib/routes.ts
  apps/web/src/sanity/happening/queries.ts
  apps/web/src/sanity/happening/requests.ts
  apps/web/src/sanity/minutes/requests.ts
  apps/web/src/sanity/posts/requests.ts
  apps/web/src/utils/prefixes.ts
Labels: manual work :muscle:

#1057 Add early registration for groups
  apps/cms/schemas/happening.tsx
  apps/web/src/actions/register.ts
  apps/web/src/app/api/sanity/sync/query.ts
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/lib/array.ts
  apps/web/src/utils/date.ts
Labels: feature :sparkles:

#1166 Fix outside click
  apps/web/src/components/desktop-navigation.tsx
Labels: feature :sparkles:

#1169 Fix initials 2
  apps/web/src/lib/initials.test.ts
Labels: testing :test_tube:

#1110 Register e2e test
  .github/workflows/ci.yaml
  apps/web/src/declarations.d.ts
  apps/web/src/env.mjs
  package.json
  packages/db/drizzle/seed.ts
  playwright/package.json
  playwright/playwright.config.ts
  playwright/web/register.spec.ts
  pnpm-lock.yaml
Labels: testing :test_tube:

#1172 Add more tests
  apps/web/src/components/deregister-button.tsx
  packages/db/drizzle/seed.ts
  playwright/helpers/sessionTest.ts
  playwright/web/gruppe.spec.ts
  playwright/web/register.spec.ts
Labels: testing :test_tube:

#1180 Better header animations
  apps/web/src/components/desktop-navigation.tsx
Labels: design 💄

#1183 Add sanity link
  apps/web/src/app/sanity/route.ts
  apps/web/src/components/user-menu.tsx
Labels: feature :sparkles:

#1196 Fix bools in happening-sidebar
  apps/web/src/components/happening-sidebar.tsx
Labels: bug :bug:

#1205 HOTFIX: Lowercase email
  packages/auth/src/auth-options.ts
Labels: bug :bug:

#1198 Add sanity proxy client
  apps/web/src/app/(default)/arrangement/[slug]/page.tsx
  apps/web/src/app/(default)/bedpres/[slug]/page.tsx
  apps/web/src/app/api/sanity/proxy/route.ts
  apps/web/src/sanity/client.ts
Labels: feature :sparkles:

#1211 fix proxy url
  apps/web/src/sanity/client.ts
Labels: bug :bug:

#1210 Add registration date
  apps/web/src/app/(default)/content.tsx
  apps/web/src/sanity/happening/queries.ts
  apps/web/src/sanity/happening/requests.ts
Labels: feature :sparkles:

#1222 top loading
  apps/web/package.json
  apps/web/src/app/layout.tsx
  pnpm-lock.yaml
Labels: feature :sparkles:

#1233 use react icons
  apps/web/package.json
  apps/web/src/app/(admin)/admin/brukere/columns.tsx
  apps/web/src/app/(default)/content.tsx
  apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
  apps/web/src/app/(default)/gruppe/[id]/_components/add-user-to-group-dialog.tsx
  apps/web/src/app/(default)/gruppe/[id]/_components/group-user-form.tsx
  apps/web/src/components/cookie-banner-client.tsx
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/components/error-box.tsx
  apps/web/src/components/event-filter.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/happening-preview-box.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/mobile-navigation.tsx
  apps/web/src/components/sidebar-layout.tsx
  apps/web/src/components/student-group-preview.tsx
  apps/web/src/components/theme-switch-button.tsx
  apps/web/src/components/typography/callout.tsx
  apps/web/src/components/ui/checkbox.tsx
  apps/web/src/components/ui/dialog.tsx
  apps/web/src/components/ui/dropdown-menu.tsx
  apps/web/src/components/ui/toast.tsx
  apps/web/src/components/user-menu.tsx
  apps/web/src/lib/routes.ts
  pnpm-lock.yaml
Labels: dependencies :handshake:

#1237 Fix pooling
  packages/db/index.ts
Labels: bug :bug:

#1238 Add logs
  apps/web/src/app/(default)/content.tsx
Labels: manual work :muscle:

#1243 Update cache on database status
  apps/web/src/utils/database-status.ts
Labels: refactoring :recycle:

#1245 Replace db status with preview status
  apps/web/src/components/site-header.tsx
  apps/web/src/utils/database-status.ts
Labels: refactoring :recycle:

#1247 Fix conflicting happenings
  apps/web/src/app/api/sanity/sync/route.ts
  packages/db/drizzle/seed.ts
  playwright/web/register.spec.ts
Labels: refactoring :recycle:, testing :test_tube:

#1253 Update /arrangementer
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/components/event-filter.tsx
Labels: feature :sparkles:

#1254 Add drizzle logger
  packages/db/index.ts
Labels: feature :sparkles:

#1267 Fix groq typo
  apps/web/src/sanity/job-ad/queries.ts
Labels: feature :sparkles:

#1270 Refactor vitest tests
  apps/web/package.json
  apps/web/src/actions/register.ts
  apps/web/src/actions/user.ts
  apps/web/src/actions/whitelist.ts
  apps/web/src/app/(admin)/admin/layout.tsx
  apps/web/src/app/api/sanity/route.ts
  apps/web/src/app/sanity/route.ts
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/components/user-menu.tsx
  apps/web/src/config.ts
  apps/web/src/data/spotrange/revalidate.ts
  apps/web/src/hooks/__tests__/use-outsideclick.test.tsx
  apps/web/src/lib/__tests__/initials.test.ts
  apps/web/src/lib/__tests__/is-board.test.ts
  apps/web/src/lib/__tests__/memberships.test.ts
  apps/web/src/lib/array.ts
  apps/web/src/lib/is-host.ts
  apps/web/src/lib/memberships.ts
  apps/web/src/utils/__tests__/date.test.ts
  apps/web/src/utils/__tests__/list.test.ts
  apps/web/src/utils/date.test.ts
  apps/web/src/utils/list.ts
  apps/web/tsconfig.json
  apps/web/vitest.config.ts
  package.json
  packages/email/package.json
  pnpm-lock.yaml
Labels: testing :test_tube:

#1262 Update header text and a11y
  apps/web/src/components/desktop-navigation.tsx
  apps/web/src/lib/routes.ts
Labels: feature :sparkles:

#1275 Add data cache to degrees
  apps/web/src/app/(admin)/admin/studieretninger/page.tsx
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/data/degrees/queries.ts
Labels: refactoring :recycle:

#1246 Add space to vertical filter buttons event side
  apps/web/src/components/event-filter.tsx
Labels: design 💄

#1279 Happening dashboard bugfixes
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/components/container.tsx
  apps/web/src/components/edit-registration-button.tsx
  apps/web/src/components/registration-table.tsx
Labels: bug :bug:

#1282 Add dark mode to code blocks
  apps/web/src/components/markdown.tsx
Labels: design 💄

#1283 Kfalvestad/dashboard bugfixes
  apps/web/src/components/registration-table.tsx
Labels: design 💄

#1288 Hermann/profil info ux
  apps/web/src/styles/globals.css
Labels: design 💄

#1294 Send email when change status to registered
  apps/web/src/actions/update-registration.ts
  apps/web/src/app/(default)/dashbord/[slug]/page.tsx
  apps/web/src/components/happening-sidebar.tsx
  apps/web/src/lib/__tests__/memberships.test.ts
  apps/web/src/lib/is-host.ts
  apps/web/src/lib/memberships.ts
  packages/email/client.ts
  packages/email/emails/got-spot-notification.tsx
  packages/email/index.ts
Labels: bug :bug:, feature :sparkles:

#1307 Remove drunk ole m
  apps/web/src/app/(default)/page.tsx
Labels: feature :sparkles:

#1310 Revalidate home
  apps/web/src/sanity/client.ts
  apps/web/src/sanity/happening/requests.ts
Labels: refactoring :recycle:

#1318 sanity fetch revalidate
  apps/web/src/sanity/client.ts
  apps/web/src/sanity/happening/requests.ts
Labels: feature :sparkles:

#1321 Fix update reg bug
  apps/web/src/actions/update-registration.ts
  apps/web/src/components/edit-registration-button.tsx
Labels: bug :bug:

#1330 Remove dead code
  apps/cms/schemas/index.ts
  apps/cms/schemas/objects/banner.tsx
  apps/cms/schemas/settings.tsx
  apps/cms/src/desk-structure.ts
  apps/web/src/actions/user.ts
  apps/web/src/components/banner.tsx
  apps/web/src/components/error-box.tsx
  apps/web/src/hooks/use-deregistration.tsx
  apps/web/src/sanity/settings/index.ts
  apps/web/src/sanity/settings/queries.ts
  apps/web/src/sanity/settings/requests.ts
  apps/web/src/sanity/settings/schemas.ts
  apps/web/src/utils/cn.ts
Labels: feature :sparkles:

#1333 Fix feedback date
  apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
Labels: bug :bug:

#1276 Profile pictures
  .env.example
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/actions/images.ts
  apps/web/src/app/(default)/auth/profil/page.tsx
  apps/web/src/components/profile-image.tsx
  apps/web/src/config.ts
  apps/web/src/lib/echogram.ts
  package.json
  packages/echogram/package.json
  packages/echogram/src/index.ts
  packages/echogram/tsconfig.json
  playwright/web/profile.spec.ts
  pnpm-lock.yaml
  turbo.json
Labels: feature :sparkles:

#1334 Use node postgres
  packages/db/drizzle/migrate.ts
  packages/db/index.ts
Labels: refactoring :recycle:

#1338 Update pnpm dev
  package.json
Labels: refactoring :recycle:

#1343 Make /arrangementer more responsive
  apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
  apps/web/src/components/event-filter.tsx
  apps/web/src/components/events-view.tsx
  apps/web/src/sanity/happening/requests.ts
Labels: refactoring :recycle:

#1342 Update echo logo url
  packages/email/emails/deregistration-notification.tsx
  packages/email/emails/got-spot-notification.tsx
  packages/email/emails/registration-confirmation.tsx
Labels: refactoring :recycle:
